# Generated by Django 5.0.2 on 2024-03-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
